apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
commonLabels:
  git-sha: 7f67e2880e7ca0527d5c4335686937f4d80af9ef
resources:
- deploy.yaml
configMapGenerator:
- literals:
  - model-revision=7f67e2880e7ca0527d5c4335686937f4d80af9ef
  - tag-name=v0.4.1
  name: model-config
  options:
    disableNameSuffixHash: true
